import type { JourneyProgress, Language, Localized, SavedRun, Weather } from './types';

export const L = (ar: string, en: string, fr: string): Localized => ({ ar, en, fr });
export const local = (value: Localized, language: Language) => value[language] || value.en;
export type Biome = 'village' | 'mountain' | 'plateau' | 'desert' | 'oasis' | 'border' | 'city' | 'medina' | 'port' | 'highland' | 'river' | 'allies' | 'citadel';
export type Point = [number, number];

export interface ActorDefinition {
  name: Localized;
  role: Localized;
  bio: Localized;
  color: number;
  hair: number;
  scarf?: number;
  elder?: boolean;
  female?: boolean;
}

export const ACTORS: Record<string, ActorDefinition> = {
  yazid: { name: L('يزيد', 'Yazid', 'Yazid'), role: L('جار العائلة', 'The family’s neighbor', 'Le voisin de la famille'), bio: L('يسقي أشجار الزيتون ويطمئن على إدريس كل صباح.', 'He waters the olive trees and checks on Idris every morning.', 'Il arrose les oliviers et rend visite à Idris chaque matin.'), color: 0x7d875a, hair: 0x605d49 },
  idris: { name: L('الحاج إدريس', 'Hadj Idris', 'Hadj Idris'), role: L('ذاكرة القرية', 'The village elder', 'La mémoire du village'), bio: L('يعرف دروب القرية وأسماء من مروا بها. صديق قديم للعائلة.', 'He remembers every road and every traveler. An old friend of the family.', 'Il connaît chaque chemin. Un vieil ami de la famille.'), color: 0xb6a787, hair: 0xbfbdb1, elder: true },
  nour: { name: L('نور', 'Nour', 'Nour'), role: L('مزارعة وقيّمة البئر', 'Farmer and well keeper', 'Agricultrice et gardienne du puits'), bio: L('تعرف أن الماء ليس رقمًا في دفتر؛ إنه حياة القرية.', 'For Nour, water is not a number in a ledger. It is the life of her village.', 'Pour Nour, l’eau est la vie du village, pas un chiffre.'), color: 0x836958, hair: 0x352b27, scarf: 0xc3b287, female: true },
  sami: { name: L('سامي', 'Sami', 'Sami'), role: L('صديق وميكانيكي', 'Friend and mechanic', 'Ami et mécanicien'), bio: L('يفضل إصلاح ما انكسر على تركه خلفه. رفيق ياسين منذ الطفولة.', 'Yassine’s childhood friend. He would rather mend something than leave it behind.', 'L’ami d’enfance de Yassine. Il préfère réparer plutôt qu’abandonner.'), color: 0x8c684e, hair: 0x292621 },
  liane: { name: L('ليان', 'Liane', 'Liane'), role: L('مستكشفة الجبال', 'Mountain pathfinder', 'Exploratrice des montagnes'), bio: L('ترسم الطرق التي تنساها الخرائط، وتنتظر رفيقها عند كل منعطف.', 'She maps forgotten paths and waits for her companion at every turning.', 'Elle dessine les chemins oubliés et attend ses compagnons à chaque détour.'), color: 0x54766d, hair: 0x3d2f27, female: true, scarf: 0xba9b6a },
  murad: { name: L('مراد', 'Murad', 'Mourad'), role: L('مهندس وباحث', 'Engineer and researcher', 'Ingénieur et chercheur'), bio: L('صمم أزرو ليعطّل الآلات بلا أذى. يبحث عن حقيقة مشروع أطلس.', 'He designed Azru to disable machines without harm. He studies the Atlas water project.', 'Il a conçu Azru pour neutraliser les machines sans blesser. Il étudie le projet Atlas.'), color: 0xaeaa86, hair: 0x5b5c50, elder: true },
  azel: { name: L('أزل', 'Azel', 'Azel'), role: L('دليل الصحراء', 'Desert guide', 'Guide du désert'), bio: L('يرى في الكثبان علامات لا يراها العابر المستعجل.', 'He reads the dunes like a familiar book, never hurrying past a sign.', 'Il lit les dunes comme un livre familier.'), color: 0x455f73, hair: 0x262d30, scarf: 0x789ba3 },
  safiya: { name: L('صفية', 'Safiya', 'Safiya'), role: L('حارسة الواحة', 'Guardian of the oasis', 'Gardienne de l’oasis'), bio: L('تحفظ أسماء الآبار والوعود التي بُنيت حولها القرية.', 'She safeguards the names of the wells and the promises built around them.', 'Elle protège les puits et les promesses sur lesquelles le village s’est construit.'), color: 0x9d7853, hair: 0x3c3028, scarf: 0xad9668, female: true },
  nabil: { name: L('نبيل', 'Nabil', 'Nabil'), role: L('أمين الرسائل', 'Keeper of letters', 'Gardien des lettres'), bio: L('يؤمن أن الرسالة المؤرخة أقوى من الإشاعة.', 'He trusts a dated letter more than a hundred rumors.', 'Il fait confiance à une lettre datée plutôt qu’aux rumeurs.'), color: 0x658078, hair: 0x44413b },
  salma: { name: L('سلمى', 'Salma', 'Salma'), role: L('مسؤولة المعبر الرسمي', 'Official crossing officer', 'Agente du passage officiel'), bio: L('تساعد المسافرين على استكمال الوثائق عبر المسار القانوني.', 'She helps travelers complete the official, lawful crossing process.', 'Elle accompagne les voyageurs dans les formalités légales.'), color: 0x45594f, hair: 0x312b25, female: true },
  kamal: { name: L('كمال', 'Kamal', 'Kamal'), role: L('موظف سجل العبور', 'Transit registrar', 'Agent du registre de transit'), bio: L('يدقق الدعوات ووثائق البحث قبل اعتمادها.', 'He verifies invitations and research papers before approval.', 'Il vérifie les invitations et les documents de recherche.'), color: 0x637268, hair: 0x484135 },
  adam: { name: L('آدم', 'Adam', 'Adam'), role: L('صحفي من تازيرا', 'Journalist from Tazira', 'Journaliste de Tazira'), bio: L('يجمع شهادات الناس قبل أن يكتب أول سطر.', 'He listens to people before writing the first line of their story.', 'Il écoute les témoins avant d’écrire la première ligne.'), color: 0x587180, hair: 0x272928 },
  hala: { name: L('هالة', 'Hala', 'Hala'), role: L('مترجمة الميناء', 'Harbor translator', 'Traductrice du port'), bio: L('تصل بين لغات المرفأ وتعرف أن الأسماء قد تخفي طريقًا.', 'She bridges the languages of the harbor and the journeys hidden in names.', 'Elle relie les langues du port et les histoires cachées dans les noms.'), color: 0xb09b7a, hair: 0x4e362b, female: true },
  zineb: { name: L('زينب', 'Zineb', 'Zineb'), role: L('ناسجة السوق القديم', 'Weaver of the old market', 'Tisserande du vieux marché'), bio: L('تعرف أختام الورش التي مرت بها القوافل.', 'She recognizes the workshop seals carried by passing caravans.', 'Elle reconnaît les sceaux des ateliers des caravanes.'), color: 0x97636b, hair: 0x4b3530, female: true },
  tarek: { name: L('طارق', 'Tarek', 'Tarek'), role: L('مؤرخ المدينة', 'Historian of the medina', 'Historien de la médina'), bio: L('يحفظ عقود الماء القديمة في أرشيف مفتوح للناس.', 'He preserves old water charters in an archive open to everyone.', 'Il conserve les chartes de l’eau dans des archives publiques.'), color: 0xb5a786, hair: 0xa5a293, elder: true },
  hana: { name: L('هناء', 'Hana', 'Hana'), role: L('خزافة وشاهدة', 'Potter and witness', 'Potière et témoin'), bio: L('تراقب ساحة السوق من ورشتها كل صباح.', 'She watches the market square from her workshop every morning.', 'Elle observe la place du marché chaque matin depuis son atelier.'), color: 0xb07955, hair: 0x3b302a, female: true },
  mira: { name: L('ميرا', 'Mira', 'Mira'), role: L('رسامة خرائط أوردل', 'Ordel harbor cartographer', 'Cartographe du port d’Ordel'), bio: L('ترسم البحر كما يراه البحارة، لا كما تريده الشركات.', 'She maps the sea as sailors see it, not as companies wish it to be.', 'Elle cartographie la mer des marins, pas celle des compagnies.'), color: 0x566679, hair: 0x936342, female: true },
  ren: { name: L('رين', 'Ren', 'Ren'), role: L('قيّم أرشيف فيلورا', 'Velora archive keeper', 'Archiviste de Velora'), bio: L('يؤمن أن لكل توقيع صاحبًا ولكل وعد مسؤولية.', 'Every signature has an author; every promise carries responsibility.', 'Chaque signature a un auteur, chaque promesse une responsabilité.'), color: 0x8c6659, hair: 0x252a29 },
  ines: { name: L('إيناس', 'Ines', 'Inès'), role: L('مهندسة أنهار إيفارا', 'River engineer of Ivara', 'Ingénieure des rivières d’Ivara'), bio: L('تجري قياساتها مع السكان لا بعيدًا عنهم.', 'She takes her measurements alongside the residents, never apart from them.', 'Elle réalise ses mesures avec les habitants, jamais loin d’eux.'), color: 0x517b6c, hair: 0x292826, female: true },
  amina: { name: L('أمينة', 'Amina', 'Amina'), role: L('والدة ياسين', 'Yassine’s mother', 'La mère de Yassine'), bio: L('لم تطفئ مصباح البيت طوال غياب ابنيها.', 'She kept the light on while both her sons were away.', 'Elle a gardé la lumière allumée en attendant ses fils.'), color: 0x997c8c, hair: 0x787568, scarf: 0xd0bdaa, female: true },
  rayan: { name: L('ريان', 'Rayan', 'Rayan'), role: L('أخ ياسين المفقود', 'Yassine’s missing brother', 'Le frère disparu de Yassine'), bio: L('مهندس مياه اكتشف اختلافًا بين التقارير وحياة الناس.', 'A water engineer who found a gap between the reports and people’s lives.', 'Un ingénieur qui a découvert un écart entre les rapports et la vie des habitants.'), color: 0x8b9a85, hair: 0x30332d },
  shadow: { name: L('ناصر / الظل', 'Nacer / The Shadow', 'Nacer / L’Ombre'), role: L('مدير مشروع أطلس', 'Director of the Atlas project', 'Directeur du projet Atlas'), bio: L('يختبئ وراء شبكة عقود وأسماء مستعارة.', 'He hides behind a network of contracts and borrowed names.', 'Il se cache derrière un réseau de contrats et de noms empruntés.'), color: 0x343f42, hair: 0x7d817a },
};

export interface NpcPlacement { actor: string; at: Point; ambient: Localized; companionAfter?: string; activity?: 'work' | 'walk' | 'rest' }
export interface Objective {
  id: string;
  kind: 'talk' | 'inspect' | 'reach' | 'drive' | 'chase' | 'fight' | 'deduce' | 'travel' | 'finish';
  title: Localized;
  detail: Localized;
  at: Point;
  actor?: string;
  lines?: Localized[];
  evidence?: { title: Localized; body: Localized };
  choices?: { label: Localized; correct: boolean }[];
  stealth?: boolean;
  seconds?: number;
}

export interface RegionDefinition {
  id: string;
  chapter: number;
  part?: string;
  title: Localized;
  place: Localized;
  country: Localized;
  biome: Biome;
  image: string;
  intro: Localized;
  outro: Localized;
  map: Point;
  day: number;
  span: number;
  weather: Weather;
  night?: boolean;
  returning?: boolean;
  vehicle?: Point;
  npcs: NpcPlacement[];
  objectives: Objective[];
  enemies?: { at: Point; hp: number; from: number; boss?: boolean }[];
}

const talkHint = L('اقترب من الشخصية واضغط E. يمكنك قراءة الحوار على مهل.', 'Approach and press E. Take your time with the conversation.', 'Approchez et appuyez sur E. Prenez le temps de lire.');
const inspectHint = L('اتبع العلامة الذهبية ثم اضغط E لفحص الدليل.', 'Follow the gold marker, then press E to examine the evidence.', 'Suivez le repère doré puis appuyez sur E pour examiner l’indice.');
const walkHint = L('استكشف الطريق واتبع العلامة. Shift للركض وSpace للقفز.', 'Explore the path. Shift to sprint, Space to jump.', 'Explorez le chemin. Maj pour courir, Espace pour sauter.');
const driveHint = L('اركب مركبة أسفار بـE. W/S للتسارع والرجوع، A/D للتوجيه وSpace للفرملة.', 'Enter the Asfar rover with E. W/S accelerate or reverse, A/D steer, Space brakes.', 'Montez dans Asfar avec E. W/S accélèrent ou reculent, A/D dirigent, Espace freine.');
const travelHint = L('اذهب إلى علامة الطريق واضغط E لبدء المرحلة التالية.', 'Reach the route marker and press E to continue the journey.', 'Rejoignez le repère et appuyez sur E pour poursuivre le voyage.');
const alg = L('الجزائر', 'Algeria', 'Algérie');
const taz = L('تازيرا / دولة خيالية', 'Tazira / fictional country', 'Tazira / pays fictif');

function talk(id: string, actor: string, at: Point, title: Localized, lines: Localized[]): Objective { return { id, actor, at, title, lines, kind: 'talk', detail: talkHint }; }
function inspect(id: string, at: Point, title: Localized, body: Localized, stealth = false): Objective { return { id, at, title, kind: 'inspect', detail: stealth ? L('انحنِ بـC أو زر الانحناء وافحص الأرشيف بـE. استعمل الجدران ساترًا.', 'Crouch with C, then inspect with E. Use the walls as cover.', 'Accroupissez-vous avec C, puis examinez avec E. Utilisez les murs comme abri.') : inspectHint, evidence: { title, body }, lines: [body], stealth }; }
function reach(id: string, at: Point, title: Localized, kind: 'reach' | 'drive' | 'chase' = 'reach'): Objective { return { id, at, title, kind, detail: kind === 'drive' ? driveHint : kind === 'chase' ? L('اركض إلى الكهف قبل انقضاء الوقت. احتمِ بالصخور من طائرات الظل.', 'Sprint to the cave before time runs out. Break drone fire with the rocks.', 'Courez vers la grotte avant la fin du temps. Abritez-vous derrière les rochers.' ) : walkHint, seconds: kind === 'chase' ? 65 : undefined }; }
function leave(id: string, at: Point, title: Localized): Objective { return { id, at, title, kind: 'travel', detail: travelHint }; }
function deduce(id: string, at: Point, title: Localized, body: Localized, choices: Localized[], answer: number): Objective {
  const conclusion = L(`${body.ar}\nالاستنتاج الموثق: ${choices[answer].ar}.`, `${body.en}\nRecorded conclusion: ${choices[answer].en}.`, `${body.fr}\nConclusion consignée : ${choices[answer].fr}.`);
  return { id, at, title, kind: 'deduce', detail: L('افتح لوحة الأدلة بـE واربط الشهادات. الإجابة الخاطئة لا تفقدك التقدم.', 'Open the evidence board with E and connect the testimonies. A wrong answer never erases progress.', 'Ouvrez le tableau avec E et reliez les témoignages. Une erreur n’efface pas votre progression.'), lines: [body], evidence: { title, body: conclusion }, choices: choices.map((label, i) => ({ label, correct: i === answer })) };
}

export const CAMPAIGN: RegionDefinition[] = [
  {
    id: 'village', chapter: 1, title: L('حيث تبدأ الحكاية', 'Where the Story Begins', 'Là où tout commence'), place: L('قرية تاغزوت', 'Taghzout Village', 'Village de Taghzout'), country: alg, biome: 'village', image: '/images/village-journey.jpg', map: [115, 140], day: 1, span: 90, weather: 'clear',
    intro: L('عاد ياسين من المدينة إلى قريته بعد انقطاع أخبار أخيه ريان. لا أحد يعرف أين ذهب مهندس المياه. لكن الحاج إدريس ما زال يجلس قرب شجرة الزيتون، ويتذكر آخر صباح رآه فيه.', 'Yassine returns from the city after his brother Rayan disappears. The water engineer left no farewell. Under the olive tree, Hadj Idris remembers the last morning he saw him.', 'Yassine revient de la ville après la disparition de son frère Rayan. Sous l’olivier, Hadj Idris se souvient du dernier matin où il l’a vu.'),
    outro: L('دفتر ريان يرسم طريقًا نحو ممر تالا. حمل ياسين أزرو الذي جهّزه سامي، وترك خلفه مصباح البيت مضاءً.', 'Rayan’s notebook points to Tala Pass. With Sami’s Azru in his pack, Yassine leaves the light burning at home.', 'Le carnet de Rayan indique le col de Tala. Yassine emporte Azru et laisse la lumière allumée à la maison.'),
    npcs: [
      { actor: 'idris', at: [-3, 12], activity: 'rest', ambient: L('إدريس: ماء البئر أقل هذا العام. يزيد، هل لاحظ ريان الأمر؟ يزيد: كان يقيسه كل صباح.', 'Idris: The well is lower this year. Did Rayan notice, Yazid? Yazid: He measured it every morning.', 'Idris : Le puits baisse cette année. Yazid : Rayan le mesurait chaque matin.') },
      { actor: 'yazid', at: [-5.5, 10], activity: 'walk', ambient: L('يزيد: ريان لم يترك يومًا شجرة عطشى. إدريس: وسيعود، إن قرأنا أثره كما ينبغي.', 'Yazid: Rayan never left a tree thirsty. Idris: He will return, if we read his trail well.', 'Yazid : Rayan n’a jamais laissé un arbre sans eau. Idris : Il reviendra, si nous suivons sa trace.') },
      { actor: 'nour', at: [8, -15], activity: 'work', ambient: L('هذه الأرض تكفي الجميع حين يصل الماء إلى الجميع.', 'This land can feed everyone, if the water reaches everyone.', 'Cette terre nourrit chacun, si l’eau arrive jusqu’à chacun.') },
      { actor: 'sami', at: [2, -40], activity: 'work', ambient: L('سامي: سأصلح مضخة القرية قبل المساء. الطريق إلى تالا طويل.', 'Sami: I will have the village pump fixed by evening. Tala is a long way.', 'Sami : La pompe sera réparée ce soir. Tala est loin.') },
    ],
    objectives: [
      talk('v-idris', 'idris', [-3, 12], L('تحدث مع الحاج إدريس', 'Speak with Hadj Idris', 'Parlez à Hadj Idris'), [L('ياسين، ريان لم يترككم. رأيته يحمل دفتر القياسات إلى البئر. قال إن الأرقام في تقارير أطلس لا تشبه ما يراه الناس.', 'Rayan did not abandon you. He took his measuring notebook to the well. He said the Atlas reports no longer matched what people could see.', 'Rayan ne vous a pas abandonnés. Il disait que les rapports Atlas ne correspondaient plus à la réalité.'), L('افحص البئر ثم اسأل نور عند الحقول. إن ترك أخوك أثرًا فستعرف كيف تقرأه.', 'Examine the well, then find Nour by the fields. You will recognize your brother’s trail.', 'Examine le puits, puis demande à Nour près des champs. Tu reconnaîtras la trace de ton frère.')]),
      inspect('v-well', [-8, -5], L('افحص علامات البئر', 'Examine the well markings', 'Examinez les marques du puits'), L('كتب ريان: «المنسوب الحقيقي أقل من التقرير. 17 / أطلس». العلامة مرسومة حديثًا فوق الحجر.', 'Rayan wrote: “Actual level below the report. 17 / Atlas.” The mark is fresh on the stone.', 'Rayan a écrit : « Niveau réel inférieur au rapport. 17 / Atlas. » La marque est récente.')),
      reach('v-fields', [8, -10], L('استكشف الحقول', 'Explore the fields', 'Explorez les champs')),
      talk('v-nour', 'nour', [8, -15], L('اسأل نور عن ريان', 'Ask Nour about Rayan', 'Interrogez Nour sur Rayan'), [L('ساعدني في فتح الساقية، ثم ترك حقيبته قرب مخزن الحبوب. كان ينتظر مستكشفة اسمها ليان.', 'He helped clear the channel, then left his notebook by the grain store. He was waiting for an explorer named Liane.', 'Il a dégagé le canal, puis laissé son carnet près du grenier. Il attendait une exploratrice nommée Liane.')]),
      inspect('v-notebook', [-6, -31], L('اعثر على دفتر ريان', 'Recover Rayan’s notebook', 'Retrouvez le carnet de Rayan'), L('خريطة ممر تالا، وملاحظة: «الظل الأسود ليس شخصًا واحدًا. اتبع العقود، لا الشائعات». هناك عنوان مراد في الهضاب.', 'A sketch of Tala Pass: “The Black Shadow is more than one person. Follow the contracts, not the rumors.” Murad’s plateau address is on the back.', 'Un croquis du col de Tala : « Suis les contrats, pas les rumeurs. » Au dos, l’adresse de Mourad sur les plateaux.')),
      talk('v-sami', 'sami', [2, -40], L('جهّز الرحلة مع سامي', 'Prepare the journey with Sami', 'Préparez le voyage avec Sami'), [L('هذا أزرو؛ نبضته تعطل الآلات ولا تؤذي الناس. F للإطلاق وR للشحن. جرّبه على الهدف إن أردت. سألقاك عند محطة مراد.', 'This is Azru. Its pulse disables machines, not people. F to fire, R to recharge. Try the practice target if you wish. I will meet you at Murad’s station.', 'Voici Azru. Son impulsion neutralise les machines. F pour tirer, R pour recharger. Je te retrouverai à la station de Mourad.')]),
      leave('v-depart', [0, -58], L('غادر نحو ممر تالا', 'Leave for Tala Pass', 'Partez vers le col de Tala')),
    ],
  },
  {
    id: 'mountains', chapter: 2, title: L('الطريق إلى الجبال', 'The Road to the Mountains', 'La route des montagnes'), place: L('ممر تالا', 'Tala Pass', 'Col de Tala'), country: alg, biome: 'mountain', image: '/images/atlas-mountains.jpg', map: [159, 123], day: 2, span: 112, weather: 'clear',
    intro: L('يتحول التراب إلى صخر، وتضيق الطريق بين أشجار الأرز. عند الجسر، تراجع ليان علامات رسمها ريان قبل اختفائه.', 'Dirt gives way to stone. Cedars close around the narrow road. At the bridge, Liane studies marks Rayan left before he vanished.', 'La terre devient pierre. Au milieu des cèdres, Liane examine les marques laissées par Rayan.'),
    outro: L('في الكهف، ظهرت خريطة شبكة من محطات الماء تتجه جنوبًا. لم يعد البحث عن ريان رحلة ياسين وحده.', 'In the cave, a map connects a chain of water stations to the south. Yassine no longer travels alone.', 'Dans la grotte, une carte relie des stations d’eau vers le sud. Yassine ne voyage plus seul.'),
    npcs: [{ actor: 'liane', at: [3, 12], companionAfter: 'm-liane', activity: 'work', ambient: L('ليان، عبر الراديو: علامات الطريق ما زالت هنا. سأنتظر عند الجسر، لن أترك أحدًا خلفي.', 'Liane, on the radio: The trail marks are still here. I will wait at the bridge. Nobody gets left behind.', 'Liane, à la radio : Les marques sont encore là. J’attends au pont. Personne ne reste derrière.') }],
    objectives: [
      talk('m-liane', 'liane', [3, 12], L('اقترب من ليان', 'Meet Liane by the trail', 'Rencontrez Liane'), [L('أعرف ذلك الدفتر. ساعدت ريان في قياس النبع. ترك خريطة في الكهف بعدما بدأت طائرات غريبة تتبعه.', 'I know that notebook. I helped Rayan measure the spring. He left a map in the cave when strange drones began following him.', 'Je connais ce carnet. J’ai aidé Rayan à mesurer la source. Il a caché une carte dans la grotte quand les drones l’ont suivi.'), L('سأرافقك. نعبر الجسر واحدًا بعد الآخر، ثم نصل إلى مدخل الكهف الشمالي.', 'I will come with you. Across the bridge, then north to the cave entrance.', 'Je t’accompagne. Traversons le pont, puis rejoignons la grotte au nord.')]),
      reach('m-bridge', [0, -23], L('اعبر جسر الأرز', 'Cross the cedar bridge', 'Traversez le pont des cèdres')),
      reach('m-chase', [0, -52], L('اهرب من المطاردة إلى الكهف', 'Escape the pursuit to the cave', 'Échappez à la poursuite vers la grotte'), 'chase'),
      inspect('m-map', [-5, -60], L('استعد الخريطة الجنوبية', 'Recover the southern map', 'Récupérez la carte du sud'), L('الخريطة تصل بين ممر تالا ومحطة السهوب ثم واحة نمار. كل موقع يحمل الرقم 17 نفسه.', 'The map links Tala Pass, the Steppe Station, and Namar Oasis. Every location bears the same number: 17.', 'La carte relie Tala, la station des steppes et l’oasis de Namar. Le nombre 17 figure partout.')),
      talk('m-promise', 'liane', [0, -60], L('اربط الخريطة مع ليان', 'Read the map with Liane', 'Lisez la carte avec Liane'), [L('هذه ليست طريق هرب؛ إنها سلسلة قياسات. مراد في المحطة التالية سيفهم الأرقام. سأبقى على اتصال بك.', 'This is not an escape route. It is a chain of measurements. Murad at the next station will understand. I will stay in touch.', 'Ce n’est pas une fuite, mais une série de mesures. Mourad comprendra. Je reste en contact.')]),
      leave('m-depart', [0, -82], L('انزل إلى الهضاب', 'Descend to the plateaus', 'Descendez vers les plateaux')),
    ], enemies: [{ at: [-1, -8], hp: 2, from: 2 }, { at: [1, -11], hp: 2, from: 2 }],
  },
  {
    id: 'plateaus', chapter: 3, title: L('الأفق المفتوح', 'The Open Horizon', 'L’horizon ouvert'), place: L('محطة السهوب', 'Steppe Station', 'Station des steppes'), country: alg, biome: 'plateau', image: '/images/village-journey.jpg', map: [139, 185], day: 3, span: 130, weather: 'clear', vehicle: [-3, 14],
    intro: L('تتسع السماء فوق الهضاب. قرب محطة طريق صغيرة، ينتظر مراد وصول قطع المضخة التي وعد بها سامي.', 'The sky opens over the plateaus. At a roadside station, Murad awaits the pump parts Sami promised.', 'Le ciel s’ouvre au-dessus des plateaux. Mourad attend les pièces de pompe promises par Sami.'),
    outro: L('تطابقت سجلات المحطة مع خريطة ريان. عقود مزورة تسحب الماء جنوبًا، ودليل اسمه أزل ينتظر على عتبة الصحراء.', 'The station ledger matches Rayan’s map. Forged contracts are moving water south. A guide named Azel waits at the edge of the desert.', 'Le registre confirme la carte. Des contrats falsifiés détournent l’eau. Azel attend à la lisière du désert.'),
    npcs: [{ actor: 'murad', at: [-5, 10], activity: 'work', ambient: L('مراد: سامي، المحطة تحتاج القطعة لا وعدًا جديدًا. سامي، عبر الراديو: أرسلها مع ياسين، سأنتظر في الجنوب.', 'Murad: Sami, the station needs the part, not another promise. Sami, on radio: Send Yassine. I will meet him south.', 'Mourad : Sami, il nous faut la pièce. Sami, à la radio : Envoie Yassine, je l’attends au sud.') }, { actor: 'sami', at: [7, -77], activity: 'work', ambient: L('هذه أسفار. بطيئة في الانعطاف، لكنها لا تخذلك في الطريق.', 'That is Asfar. Take its corners gently and it will never let you down.', 'C’est Asfar. Prends les virages doucement, elle ne t’abandonnera pas.') }],
    objectives: [
      talk('p-murad', 'murad', [-5, 10], L('قابل مراد في المحطة', 'Meet Murad at the station', 'Retrouvez Mourad à la station'), [L('أطلس بدأ مشروعًا لتوزيع الماء بعدل. لكن تقرير أخيك يشير إلى محطات غير موجودة. خذ مركبة أسفار واتبع نقطتي الطريق لتصل إلى السجل الجنوبي.', 'Atlas began as a fair-water project. Your brother found reports of stations that do not exist. Take Asfar through the two road markers to the southern ledger.', 'Atlas devait partager l’eau équitablement. Ton frère a trouvé des stations fictives. Prends Asfar et suis les deux repères vers le registre sud.')]),
      reach('p-drive1', [0, -20], L('قد أسفار إلى أول محطة طريق', 'Drive Asfar to the first waypoint', 'Conduisez Asfar au premier repère'), 'drive'),
      reach('p-drive2', [6, -52], L('أوصل القطعة إلى المحطة الجنوبية', 'Deliver the part to the southern station', 'Livrez la pièce à la station sud'), 'drive'),
      inspect('p-ledger', [-7, -62], L('افحص سجل توزيع الماء', 'Examine the water ledger', 'Examinez le registre de l’eau'), L('المحطة 17 تستلم الماء مرتين على الورق ولا تستلمه في الواقع. ختم الشحنة يحمل اسم واحة نمار.', 'Station 17 receives water twice on paper, and never in reality. The shipment seal names Namar Oasis.', 'La station 17 reçoit l’eau deux fois sur papier, jamais en réalité. Le sceau indique Namar.')),
      talk('p-sami', 'sami', [7, -77], L('راجع الطريق مع سامي', 'Check the route with Sami', 'Vérifiez la route avec Sami'), [L('جهزت مركبة أخرى للصحراء. أزل يعرف الكثبان. إن وجدت ريان، أخبره أن مضخة القرية تعمل من جديد.', 'I have prepared another rover for the dunes. Azel knows the way. Tell Rayan the village pump is working again.', 'Un autre véhicule est prêt pour les dunes. Azel connaît la route. Dis à Rayan que la pompe du village fonctionne.')]),
      leave('p-depart', [0, -99], L('اتبع الطريق الجنوبي', 'Take the southern road', 'Prenez la route du sud')),
    ],
  },
  {
    id: 'desert', chapter: 4, title: L('على عتبة الرمل', 'At the Edge of the Sand', 'Au seuil du sable'), place: L('درب نمار', 'The Namar Trail', 'La piste de Namar'), country: alg, biome: 'desert', image: '/images/sahara-dunes.jpg', map: [104, 259], day: 4, span: 175, weather: 'dust', vehicle: [-3, 15],
    intro: L('تتباعد الأعشاب ثم تختفي. يمد الرمل خطوطه حول الطريق، وينتظر أزل قرب مركبة أعدها سامي لهذه الأرض.', 'Grass thins and disappears. Sand draws new lines around the road. Azel waits beside the rover Sami prepared for the dunes.', 'L’herbe disparaît peu à peu. Azel attend près du véhicule préparé pour les dunes.'),
    outro: L('لم تكن الواحة مفقودة؛ كان اسمها محذوفًا من الخرائط الحديثة. خلف الكثبان ظهرت أضواء نمار الأولى.', 'The oasis was never lost. Its name had been removed from modern maps. Beyond the dunes, Namar’s first lights appear.', 'L’oasis n’était pas perdue : son nom avait été effacé des cartes. Les lumières de Namar apparaissent.'),
    npcs: [{ actor: 'azel', at: [5, 10], companionAfter: 'd-azel', activity: 'rest', ambient: L('الريح تغير شكل الرمل، لكنها لا تغير موضع النجوم. لا تترك الطريق وحدك.', 'The wind changes the sand, not the stars. Do not leave the trail alone.', 'Le vent change le sable, pas les étoiles. Ne quitte pas la piste seul.') }],
    objectives: [
      talk('d-azel', 'azel', [5, 10], L('قابل أزل، دليل الصحراء', 'Meet Azel, the desert guide', 'Rencontrez Azel, guide du désert'), [L('وصلني خبرك من سامي. نمار بعيدة، والسيارة العادية لن تكفي. سأرافقك في أسفار. اتبع حجارة الطريق ولا تطارد السراب.', 'Sami sent word. Namar is far; an ordinary car will not do. I will ride with you. Follow the trail stones, not the mirage.', 'Sami m’a prévenu. Namar est loin. Je monte avec toi dans Asfar. Suis les pierres, pas le mirage.')]),
      reach('d-dunes', [0, -30], L('اعبر بوابة الكثبان بالمركبة', 'Drive through the dune gateway', 'Traversez la porte des dunes en véhicule'), 'drive'),
      reach('d-road', [-3, -78], L('اتبع درب الحجارة', 'Follow the stone trail', 'Suivez la piste de pierres'), 'drive'),
      reach('d-spring', [7, -96], L('توقف عند النبع الجاف', 'Stop at the dry spring', 'Arrêtez-vous à la source asséchée')),
      inspect('d-marker', [7, -100], L('اقرأ نقش النبع', 'Read the spring inscription', 'Lisez l’inscription de la source'), L('النبع مسجل باسم أهالي نمار منذ أجيال. في سجلات أطلس صار «أرضًا بلا سكان». أزل يشير إلى الضوء خلف التلة.', 'For generations the spring belonged to Namar’s residents. Atlas now calls it “uninhabited land.” Azel points to a light beyond the ridge.', 'La source appartient aux habitants depuis des générations. Atlas parle de « terre inhabitée ». Azel montre une lumière.')),
      leave('d-depart', [0, -145], L('ادخل الواحة المخفية', 'Enter the hidden oasis', 'Entrez dans l’oasis cachée')),
    ],
  },
  {
    id: 'oasis', chapter: 5, title: L('رسالة تحت النجوم', 'A Letter Beneath the Stars', 'Une lettre sous les étoiles'), place: L('واحة نمار', 'Namar Oasis', 'Oasis de Namar'), country: alg, biome: 'oasis', image: '/images/oasis-night.jpg', map: [177, 294], day: 5, span: 103, weather: 'clear', night: true,
    intro: L('تنعكس مصابيح قرية صغيرة فوق الماء. تصمت السوق مع حلول الليل، لكن صفية وقيّم الرسائل نبيل ينتظران من يسمع حكايتهما.', 'Lanterns reflect across the oasis. The market quiets at night, but Safiya and Nabil are waiting for someone to hear their story.', 'Les lanternes se reflètent sur l’oasis. Safiya et Nabil attendent quelqu’un prêt à les écouter.'),
    outro: L('الرسالة تقود إلى صحفي في تازيرا. أرفق نبيل دعوة بحث رسمية؛ الطريق التالي يمر من معبر قانوني، لا من ثغرة في الحدود.', 'The letter points to a journalist in Tazira. Nabil includes an official research invitation. The next road goes through a lawful crossing.', 'La lettre mène à un journaliste de Tazira. Nabil joint une invitation officielle : la prochaine route passe par un poste légal.'),
    npcs: [{ actor: 'safiya', at: [-3, 12], ambient: L('صفية: لا تطفئ المصابيح يا نبيل؛ المسافرون يرونها من بعيد. نبيل: والرسالة ما زالت تنتظر صاحبها.', 'Safiya: Keep the lanterns lit, Nabil. Travelers see them from the dunes. Nabil: The letter is still waiting.', 'Safiya : Garde les lanternes allumées. Nabil : La lettre attend toujours.') }, { actor: 'nabil', at: [9, -29], activity: 'work', ambient: L('الأوراق أمانة، والأسماء ليست للبيع.', 'The letters are entrusted to us. Their names are not for sale.', 'Ces lettres nous sont confiées. Les noms ne sont pas à vendre.') }],
    objectives: [
      talk('o-safiya', 'safiya', [-3, 12], L('استمع إلى صفية', 'Listen to Safiya', 'Écoutez Safiya'), [L('ريان نام هنا ليلة واحدة. كان يتبع عقدًا محونا منه نحن، سكان الواحة. اذهب إلى الحديقة لترى سجل البئر.', 'Rayan stayed one night. He was following a contract from which we, the people of the oasis, had been erased. See the well register in the garden.', 'Rayan est resté une nuit. Un contrat avait effacé les habitants. Le registre du puits est dans le jardin.')]),
      inspect('o-garden', [-9, -12], L('اقرأ سجل الحديقة', 'Read the garden register', 'Lisez le registre du jardin'), L('سبع وعشرون عائلة تعيش حول البئر. التقرير الحديث يسجل صفرًا. التزوير يمحو السكان قبل أن يحوّل الماء.', 'Twenty-seven families live around this well. The new report records zero. The forgery erases people before diverting their water.', 'Vingt-sept familles vivent ici. Le rapport indique zéro. La fraude efface les habitants avant de détourner leur eau.')),
      talk('o-nabil', 'nabil', [9, -29], L('تحدث مع نبيل عند الأرشيف', 'Find Nabil at the archive', 'Trouvez Nabil aux archives'), [L('ريان أودع رسالة باسم آدم في تازيرا. طائرات الشبكة تفحص الأرشيف ليلًا. مرّ منخفضًا خلف الجدار، وخذ النسخة ثم الدعوة المختومة.', 'Rayan left a letter for Adam in Tazira. Network drones scan the archive at night. Crouch behind the wall, recover the copy and its stamped invitation.', 'Rayan a laissé une lettre pour Adam. Les drones surveillent les archives. Passe accroupi derrière le mur et récupère la copie.')]),
      inspect('o-archive', [-7, -42], L('تسلل إلى الأرشيف ليلًا', 'Recover the archive copy at night', 'Récupérez la copie de nuit'), L('رسالة ريان: «آدم، السجلات الأصلية موزعة بين أوردل وفيلورا وإيفارا. لا تنشر الاتهام دون توقيعاتها الثلاثة».', 'Rayan’s letter: “Adam, the originals are split between Ordel, Velora and Ivara. Do not publish an accusation without all three signatures.”', 'Lettre de Rayan : « Adam, les originaux sont à Ordel, Velora et Ivara. Il nous faut les trois signatures. »'), true),
      inspect('o-invitation', [4, -56], L('خذ الدعوة الرسمية', 'Collect the official invitation', 'Prenez l’invitation officielle'), L('دعوة من دار الوثائق في تازيرا، وتصريح بحث معتمد باسم ياسين. سيُدقق في المعبر الرسمي الخيالي «ميزان».', 'An invitation from Tazira’s document house and a research application in Yassine’s name. They will be checked at the fictional Mizan official crossing.', 'Une invitation officielle et une demande de recherche au nom de Yassine, à vérifier au passage fictif de Mizan.')),
      leave('o-depart', [0, -72], L('اتجه إلى معبر ميزان الرسمي', 'Travel to the official Mizan crossing', 'Rejoignez le passage officiel de Mizan')),
    ], enemies: [{ at: [5, -38], hp: 2, from: 3 }, { at: [-4, -55], hp: 2, from: 3 }],
  },
  {
    id: 'border', chapter: 6, title: L('أبواب مفتوحة', 'Open Gates', 'Des portes ouvertes'), place: L('معبر ميزان الرسمي الخيالي', 'Mizan official crossing / fictional', 'Passage officiel fictif de Mizan'), country: L('ممر قصصي بين الجزائر وتازيرا', 'A fictional Algeria–Tazira corridor', 'Corridor narratif Algérie–Tazira'), biome: 'border', image: '/images/sahara-dunes.jpg', map: [260, 251], day: 6, span: 104, weather: 'clear',
    intro: L('معبر ميزان مكان خيالي لا يمثل حدودًا حقيقية. يتوقف ياسين في ساحة المسافرين ويقدم طلب البحث عبر الموظفين المعتمدين.', 'Mizan is a fictional crossing, not a real border route. Yassine stops in the travelers’ courtyard to submit his research application to the officials.', 'Mizan est un passage fictif, pas un itinéraire frontalier réel. Yassine présente sa demande aux agents officiels.'),
    outro: L('اكتملت الوثائق واعتمدت سلمى العبور الرسمي. وراء البوابة تتبدل لافتات الطريق، ويبدأ فصل جديد من الرحلة.', 'The documents are verified. Salma approves the official passage. Beyond the gate, the road signs change and a new chapter begins.', 'Les documents sont vérifiés. Salma autorise le passage officiel. De l’autre côté, les panneaux changent.'),
    npcs: [{ actor: 'salma', at: [-4, 12], activity: 'work', ambient: L('سلمى: أهلًا بكم. التحقق من الدعوات في المكتب الأيمن، ثم تعودون لاعتماد التصريح.', 'Salma: Welcome. Invitations are verified at the right-hand desk, then return for approval.', 'Salma : Bienvenue. Vérifiez les invitations au bureau de droite, puis revenez pour l’autorisation.') }, { actor: 'kamal', at: [7, -23], activity: 'work', ambient: L('كل مسافر له سجل، وكل عبور له اعتماد.', 'Every traveler has a record; every passage needs approval.', 'Chaque voyageur a un dossier et chaque passage une autorisation.') }],
    objectives: [
      talk('b-salma', 'salma', [-4, 12], L('قدم الطلب إلى سلمى', 'Submit your application to Salma', 'Présentez votre demande à Salma'), [L('دعوتك سليمة مبدئيًا. استلم نسخة الملف من الشباك، ثم اطلب من كمال مطابقة الختم. لن نفتح البوابة قبل الاعتماد.', 'Your invitation appears in order. Collect your file copy, then ask Kamal to verify the seal. The gate opens only after approval.', 'L’invitation paraît correcte. Prenez la copie du dossier et faites vérifier le sceau par Kamal. La porte attendra l’autorisation.')]),
      inspect('b-file', [7, -5], L('استلم ملف المسافر', 'Collect your traveler file', 'Retirez votre dossier'), L('هوية ياسين، دعوة الأرشيف، وبيان المعدات غير القتالية. الملف مكتمل وينتظر المصادقة الرسمية.', 'Yassine’s identity, the archive invitation and a declaration of non-lethal research equipment. The complete file awaits official verification.', 'Identité, invitation et déclaration de matériel non létal. Le dossier attend la vérification officielle.')),
      talk('b-kamal', 'kamal', [7, -23], L('صادق على الدعوة لدى كمال', 'Have Kamal verify the invitation', 'Faites vérifier l’invitation par Kamal'), [L('الختم يطابق سجل دار الوثائق. اعتمدت الدعوة وحددت غرض الزيارة: بحث مدني. عد إلى سلمى لتستلم تصريح العبور.', 'The seal matches the document-house register. The visit is approved for civil research. Return to Salma for your crossing permit.', 'Le sceau correspond au registre. La recherche civile est approuvée. Retournez auprès de Salma pour le permis.')]),
      talk('b-permit', 'salma', [-4, 12], L('استلم تصريح العبور الرسمي', 'Receive the official crossing permit', 'Recevez le permis officiel'), [L('تمت المصادقة. تصريحك معتمد والبوابة مفتوحة الآن. طريقك واضح وقانوني. رحلة آمنة يا ياسين.', 'Verification complete. Your permit is approved and the gate is now open. Your passage is lawful. Travel safely, Yassine.', 'Vérification terminée. Le permis est approuvé et la porte est ouverte. Bon voyage, Yassine.')]),
      reach('b-gate', [0, -54], L('اعبر البوابة بعد اعتماد التصريح', 'Pass through the approved gate', 'Passez la porte après autorisation')),
      leave('b-depart', [0, -74], L('تابع نحو تازيرا', 'Continue into Tazira', 'Continuez vers Tazira')),
    ],
  },
  {
    id: 'tazira', chapter: 7, title: L('أصوات مدينة جديدة', 'Voices of a New City', 'Les voix d’une nouvelle ville'), place: L('نيرايا', 'Neraya', 'Neraya'), country: taz, biome: 'city', image: '/images/algiers-hero.jpg', map: [341, 216], day: 7, span: 93, weather: 'clear',
    intro: L('في نيرايا، تمتزج العربية بلغة محلية خيالية اسمها «تازيري». أبواب فيروزية وأقواس بيضاء تقود إلى المرفأ حيث ينتظر آدم.', 'In Neraya, Arabic mingles with the fictional Taziri language. Turquoise doors and white arcades lead to the harbor, where Adam waits.', 'À Neraya, l’arabe côtoie la langue fictive taziri. Des portes turquoise et des arcades blanches mènent au port où attend Adam.'),
    outro: L('ترجمت هالة اسمًا في سجل المرفأ: «دار الينابيع». آدم يعرفه؛ إنه الأرشيف في المدينة القديمة.', 'Hala translates a harbor entry: “House of Springs.” Adam knows the name. It is the archive in the old medina.', 'Hala traduit une mention : « Maison des sources ». Adam connaît les archives de la vieille médina.'),
    npcs: [{ actor: 'adam', at: [-3, 12], companionAfter: 't-adam', ambient: L('آدم: «أمان تيرا» تعني أهلًا بمن يأتي بسلام. هذه العبارة ستسمعها كثيرًا هنا.', 'Adam: “Aman tira” welcomes those who arrive in peace. You will hear it often here.', 'Adam : « Aman tira » accueille ceux qui viennent en paix. Tu l’entendras souvent.') }, { actor: 'hala', at: [8, -18], activity: 'work', ambient: L('هالة: «نارا» هي الماء في تازيري. لكن عقد الماء ليس مجرد ترجمة.', 'Hala: “Nara” means water in Taziri. A water charter is more than a translation.', 'Hala : « Nara » veut dire eau en taziri. Une charte de l’eau n’est pas une simple traduction.') }],
    objectives: [
      talk('t-adam', 'adam', [-3, 12], L('تعرف إلى آدم', 'Meet Adam', 'Rencontrez Adam'), [L('وصلت رسالة نبيل. ريان أرسل إليّ نسخًا ولم يصل بنفسه. أبحث عنه أيضًا. هالة تستطيع قراءة رمز الشحنة في دفتره.', 'Nabil’s letter arrived. Rayan sent copies but never came himself. I am looking for him too. Hala can translate the cargo code.', 'La lettre de Nabil est arrivée. Rayan a envoyé des copies, sans venir lui-même. Hala peut traduire le code.'), L('سأرافقك عبر الساحة. هنا الناس يعرفون بعضهم؛ اسأل قبل أن تتهم.', 'I will walk with you. People know one another here. Ask before you accuse.', 'Je t’accompagne. Ici les gens se connaissent : demande avant d’accuser.')]),
      reach('t-square', [0, -6], L('استكشف ساحة نيرايا', 'Explore Neraya’s square', 'Explorez la place de Neraya')),
      talk('t-hala', 'hala', [8, -18], L('استعن بهالة لترجمة الرمز', 'Ask Hala to translate the code', 'Demandez à Hala de traduire le code'), [L('الرمز لا يصف حمولة، بل عقد انتفاع. كلمة «أمان» حُذفت؛ من «عهد الماء للجميع» صار الاسم «امتياز الماء». ابحث عن السجل الأصلي في المرفأ.', 'The code describes a charter, not cargo. One word was removed: “the water covenant for all” became “the water concession.” Find the original harbor entry.', 'Le code désigne une charte. Un mot supprimé transforme « l’eau pour tous » en « concession d’eau ». Cherchez le registre original.')]),
      inspect('t-harbor', [-7, -30], L('افحص سجل المرفأ', 'Inspect the harbor register', 'Consultez le registre du port'), L('المستلم: دار الينابيع في المدينة القديمة. النسخة الأصلية تحمل ثلاثة شهود من ورش مختلفة.', 'Recipient: House of Springs, old medina. The original carries three witnesses from separate workshops.', 'Destinataire : Maison des sources, vieille médina. Trois ateliers ont servi de témoins.')),
      talk('t-route', 'adam', [0, -32], L('اتفق مع آدم على الخطوة التالية', 'Plan the next step with Adam', 'Préparez la suite avec Adam'), [L('لا تكفي شهادة واحدة. سنتحدث إلى الناس الثلاثة في المدينة القديمة ونربط رواياتهم.', 'One witness is not enough. We will speak to all three in the medina and connect their stories.', 'Un seul témoin ne suffit pas. Parlons aux trois et relions leurs récits.')]),
      leave('t-depart', [0, -63], L('ادخل المدينة القديمة', 'Enter the old medina', 'Entrez dans la vieille médina')),
    ],
  },
  {
    id: 'medina', chapter: 8, title: L('ثلاث شهادات وحقيقة واحدة', 'Three Witnesses, One Truth', 'Trois témoins, une vérité'), place: L('مدينة صفرا القديمة', 'Sefra Old Medina', 'Vieille médina de Sefra'), country: taz, biome: 'medina', image: '/images/algiers-hero.jpg', map: [389, 190], day: 8, span: 99, weather: 'clear',
    intro: L('في أزقة صفرا، تعمل زينب على نولها ويصنف طارق أوراقه، بينما تطلي هناء آخر أواني النهار. كل واحد منهم رأى جزءًا مختلفًا من الحكاية.', 'In Sefra’s lanes, Zineb works her loom, Tarek sorts his papers and Hana finishes her pottery. Each saw a different part of the story.', 'Dans les ruelles, Zineb tisse, Tarek classe ses papiers et Hana termine ses poteries. Chacun a vu un fragment de l’histoire.'),
    outro: L('الأختام ليست آثارًا مسروقة، بل توقيعات لعقود ماء مزورة. لإثبات الحقيقة، يجب العثور على النسخ الأصلية في ثلاث دول خيالية.', 'The seals are not stolen artifacts. They are signatures on forged water charters. Proving it requires originals from three fictional countries.', 'Les sceaux ne sont pas des antiquités volées, mais les signatures de chartes falsifiées. Il faut les originaux de trois pays fictifs.'),
    npcs: [{ actor: 'zineb', at: [-8, 7], activity: 'work', ambient: L('زينب: لا تتشابه الأختام مهما تشابهت الألوان.', 'Zineb: Two seals are never the same, even if their colors match.', 'Zineb : Deux sceaux ne sont jamais identiques.') }, { actor: 'tarek', at: [8, -15], activity: 'rest', ambient: L('طارق: الأرشيف مفتوح. الحقيقة لا تحتاج بابًا مغلقًا.', 'Tarek: The archive is open. Truth has no need of a locked door.', 'Tarek : Les archives sont ouvertes. La vérité n’a pas besoin d’une porte fermée.') }, { actor: 'hana', at: [-8, -35], activity: 'work', ambient: L('هناء: تأتي القوافل وتذهب، وتبقى آثارها على الطين.', 'Hana: Caravans come and go. Their traces remain in the clay.', 'Hana : Les caravanes passent. Leurs traces restent dans l’argile.') }],
    objectives: [
      talk('s-zineb', 'zineb', [-8, 7], L('استمع إلى زينب', 'Hear Zineb’s testimony', 'Écoutez Zineb'), [L('الختم الأزرق صنع في أوردل. رأيته على صناديق أوراق، لا على آثار أو ذهب. أصحابها كانوا يخفون أسماء القرى.', 'The blue seal was made in Ordel. I saw it on boxes of papers, not gold or artifacts. The owners were hiding village names.', 'Le sceau bleu vient d’Ordel. Les caisses contenaient des papiers, pas de l’or. On y cachait les noms de villages.')]),
      talk('s-tarek', 'tarek', [8, -15], L('راجع العقود مع طارق', 'Read the charters with Tarek', 'Lisez les chartes avec Tarek'), [L('النص الأصلي يضمن الماء للسكان. النسخة الجديدة تمنح الشركة حق إغلاق الآبار. توقيع المدير ناصر تكرر في النسختين، بتاريخين لا يجتمعان.', 'The original guarantees water to residents. The new version lets a company close wells. Director Nacer’s signature appears on incompatible dates.', 'L’original garantit l’eau aux habitants. La copie autorise une société à fermer les puits. Les dates de la signature de Nacer ne concordent pas.')]),
      talk('s-hana', 'hana', [-8, -35], L('اسأل هناء عن الشحنة', 'Ask Hana about the shipment', 'Interrogez Hana sur le chargement'), [L('سمعت المرسل يقول: «نسخة للميناء، نسخة للجبال، وقياسات النهر للأخيرة». وكانت على الغلاف أسماء أوردل وفيلورا وإيفارا.', 'I heard: “One copy for the harbor, one for the mountains, and river measurements for the last.” The wrapper named Ordel, Velora and Ivara.', 'J’ai entendu : « Une copie au port, une aux montagnes, les mesures au fleuve. » L’emballage nommait Ordel, Velora et Ivara.')]),
      deduce('s-link', [0, -47], L('اربط الشهادات الثلاث', 'Connect the three testimonies', 'Reliez les trois témoignages'), L('أوراق بلا أسماء قرى، وعقود ماء تغيرت، وثلاث وجهات. ما الذي تنقله الشبكة؟', 'Papers without village names, altered water charters, three destinations. What is the network moving?', 'Des villages effacés, des chartes modifiées, trois destinations. Que transporte le réseau ?'), [L('آثارًا تاريخية للبيع', 'Historic artifacts for sale', 'Des antiquités à vendre'), L('نسخًا مزورة لعقود الماء', 'Forged copies of water charters', 'Des copies falsifiées des chartes de l’eau'), L('رسائل سفر عادية', 'Ordinary travel letters', 'De simples lettres de voyage')], 1),
      leave('s-depart', [0, -69], L('احجز العبور الرسمي إلى أوردل', 'Take the scheduled passage to Ordel', 'Prenez la liaison officielle vers Ordel')),
    ],
  },
  {
    id: 'ordel', chapter: 9, part: 'I', title: L('الرحلة عبر الدول', 'Across the Wider World', 'À travers les pays'), place: L('ميناء أستر', 'Aster Harbor', 'Port d’Aster'), country: L('أوردل / دولة خيالية', 'Ordel / fictional country', 'Ordel / pays fictif'), biome: 'port', image: '/images/ordel-harbor.jpg', map: [467, 108], day: 11, span: 98, weather: 'rain',
    intro: L('تحمل العبارة ياسين شمالًا وفق حجز رسمي. أسقف حجرية وواجهات قرميدية تحيط بميناء أستر. ميرا تعرف السفينة التي حملت السجل الأول.', 'A scheduled ferry carries Yassine north. Slate roofs and brick facades surround Aster Harbor. Mira knows which ship carried the first ledger.', 'Un ferry régulier conduit Yassine au nord. Au port d’Aster, Mira connaît le navire du premier registre.'),
    outro: L('النسخة الموثقة الأولى صارت بأمان. ختمها يحيل إلى أرشيف فيلورا في الجبال الشرقية، فتبدأ رحلة أخرى بالحجز والتصريح.', 'The first certified copy is safe. Its seal points to Velora’s mountain archive. Another authorized journey begins.', 'La première copie certifiée est en sécurité. Son sceau mène aux archives de Velora. Un nouveau voyage autorisé commence.'),
    npcs: [{ actor: 'mira', at: [-4, 12], companionAfter: 'or-mira', activity: 'work', ambient: L('ميرا: «فيل نار»، صباح هادئ بلغة المرفأ. لكنها ليست ليلة هادئة للأرشيف.', 'Mira: “Vel nar,” a calm morning in our harbor tongue. The archive has had no such calm.', 'Mira : « Vel nar », un matin calme dans notre langue. Les archives n’ont pas eu ce calme.') }],
    objectives: [
      talk('or-mira', 'mira', [-4, 12], L('قابل ميرا عند الرصيف', 'Meet Mira on the quay', 'Rencontrez Mira sur le quai'), [L('آدم أخبرني بمجيئك. استخرجت إذن الاطلاع على السجل. افحص دفتر السفينة، ثم احمِ المستودع من طائرات حاولت محو النسخة.', 'Adam told me you were coming. I obtained permission to view the ledger. Check the ship’s log, then protect the archive from the drones trying to erase it.', 'Adam m’a prévenue. J’ai obtenu l’accès au registre. Consulte le journal du navire puis protège l’archive des drones.')]),
      inspect('or-log', [7, -10], L('اقرأ دفتر السفينة', 'Read the ship’s log', 'Lisez le journal du navire'), L('وصلت صناديق أطلس قبل التاريخ المعلن بأسبوع. رقم الحمولة 17 يشير إلى أرشيف العقود، لا إلى معدات مياه.', 'The Atlas crates arrived a week before the declared date. Cargo 17 is the contract archive, not water equipment.', 'Les caisses Atlas sont arrivées une semaine avant la date déclarée. Le lot 17 contient les contrats.')),
      { id: 'or-defend', kind: 'fight', at: [0, -30], title: L('احمِ المستودع وعطّل الطائرات', 'Protect the archive: disable the drones', 'Protégez les archives : neutralisez les drones'), detail: L('وجّه الكاميرا إلى الطائرات وأطلق بـF. استخدم الصناديق ساترًا.', 'Face the drones and fire with F. Use the crates as cover.', 'Visez les drones et tirez avec F. Abritez-vous derrière les caisses.') },
      inspect('or-seal', [-6, -45], L('استلم النسخة الموثقة الأولى', 'Recover the first certified copy', 'Récupérez la première copie certifiée'), L('نسخة أوردل تثبت التاريخ الحقيقي وتوقيع ناصر الأصلي. بقي سجل التوقيع في فيلورا وقياس الماء في إيفارا.', 'Ordel’s copy proves the true date and Nacer’s original signature. Velora holds the signing register; Ivara holds the water measurements.', 'La copie d’Ordel prouve la date et la signature de Nacer. Restent le registre de Velora et les mesures d’Ivara.')),
      leave('or-depart', [0, -67], L('تابع إلى فيلورا', 'Continue to Velora', 'Continuez vers Velora')),
    ], enemies: [{ at: [-4, -27], hp: 2, from: 2 }, { at: [6, -35], hp: 3, from: 2 }],
  },
  {
    id: 'velora', chapter: 9, part: 'II', title: L('الرحلة عبر الدول', 'Across the Wider World', 'À travers les pays'), place: L('سارين، مدينة الجسور', 'Sarin, the bridge city', 'Sarin, la cité des ponts'), country: L('فيلورا / دولة خيالية', 'Velora / fictional country', 'Velora / pays fictif'), biome: 'highland', image: '/images/velora-valley.jpg', map: [584, 173], day: 15, span: 103, weather: 'clear',
    intro: L('بين غابات الأرز والأسقف الخضراء المتدرجة، يرحب رين بياسين بكلمة «ساي لوم». ويضيف مترجمًا: «ليكن طريقك واضحًا».', 'Among cedar forests and layered green roofs, Ren greets Yassine: “Sai lum.” He translates: “May your path be clear.”', 'Entre les cèdres et les toits verts, Ren accueille Yassine : « Sai lum ». Que ton chemin soit clair.'),
    outro: L('سجل فيلورا يكشف إعادة استخدام توقيع قديم على عقد جديد. بقيت شهادة النهر في إيفارا ليثبت الضرر الحقيقي.', 'Velora’s register reveals an old signature reused on a new charter. Ivara’s river must now prove the real-world harm.', 'Le registre révèle une ancienne signature réutilisée. Les mesures d’Ivara doivent prouver les conséquences.'),
    npcs: [{ actor: 'ren', at: [-3, 12], activity: 'rest', ambient: L('رين: نعبر الجسر ببطء. للأوراق القديمة هشاشة الحجارة نفسها.', 'Ren: Cross the bridge slowly. Old papers are as fragile as old stone.', 'Ren : Traverse doucement. Les vieux papiers sont fragiles comme la pierre.') }],
    objectives: [
      talk('ve-ren', 'ren', [-3, 12], L('قابل رين في سارين', 'Meet Ren in Sarin', 'Rencontrez Ren à Sarin'), [L('إذن البحث وصل قبل وصولك. ريان طلب هذا السجل قبل أشهر. توقيع ناصر موجود، لكن الصفحة التالية تحكي شيئًا آخر.', 'Your research permit arrived before you. Rayan requested this register months ago. Nacer’s signature is there, but the next page tells another story.', 'Ton autorisation est arrivée. Rayan a demandé ce registre il y a des mois. La page suivante change tout.')]),
      reach('ve-bridge', [0, -15], L('اعبر جسر الأرشيف', 'Cross the archive bridge', 'Traversez le pont des archives')),
      inspect('ve-register', [-6, -37], L('افحص سجل التوقيعات', 'Examine the signing register', 'Examinez le registre des signatures'), L('التوقيع يعود إلى ميثاق قديم يمنع احتكار الماء. استُنسخ على عقد يمنح مدير أطلس حق حجب الماء عن القرى.', 'The signature belongs to an old charter prohibiting water monopolies. It was copied onto a contract giving Atlas control over village supplies.', 'La signature vient d’une charte interdisant le monopole. Elle a été copiée sur un contrat donnant le contrôle à Atlas.')),
      deduce('ve-compare', [6, -49], L('قارن النسختين', 'Compare the two versions', 'Comparez les deux versions'), L('التوقيع متطابق، لكن النص والتاريخ مختلفان. ماذا تثبت صفحة الأرشيف الأصلية؟', 'The signatures match, but the text and date differ. What does the original archive page prove?', 'Les signatures sont identiques, mais le texte et la date changent. Que prouve l’original ?'), [L('أعيد استعمال توقيع قديم لتزوير الموافقة', 'An old signature was reused to fake approval', 'Une ancienne signature a été réutilisée pour falsifier l’accord'), L('كل العقود صحيحة لأن التوقيع موجود', 'Every contract is valid because it has a signature', 'Tous les contrats sont valides car ils sont signés'), L('لا علاقة للسجل بالقصة', 'The register is unrelated', 'Le registre n’a aucun rapport')], 0),
      leave('ve-depart', [0, -70], L('سافر إلى أنهار إيفارا', 'Travel to the rivers of Ivara', 'Partez vers les rivières d’Ivara')),
    ],
  },
  {
    id: 'ivara', chapter: 9, part: 'III', title: L('الرحلة عبر الدول', 'Across the Wider World', 'À travers les pays'), place: L('نوريا، مدينة النهر', 'Noria, the river city', 'Noria, la cité du fleuve'), country: L('إيفارا / دولة خيالية', 'Ivara / fictional country', 'Ivara / pays fictif'), biome: 'river', image: '/images/ivara-river.jpg', map: [563, 310], day: 19, span: 101, weather: 'rain',
    intro: L('يرتفع الخشب فوق الماء في نوريا. ترحب إيناس بكلمة «لوا ميري»: بيت النهر مفتوح. هنا لا يكفي العقد؛ يجب قياس ما تغير في حياة الناس.', 'In Noria, timber homes rise above the river. Ines greets him: “Lua miri,” the river’s home is open. Here the contracts must meet real measurements.', 'À Noria, les maisons s’élèvent sur l’eau. Inès dit « Lua miri », la maison du fleuve est ouverte. Les contrats rencontrent la réalité.'),
    outro: L('ثلاث نسخ وثلاث شهادات تتفق. أرسل آدم دعوة إلى بيت اللقاء؛ ليان ومراد وسامي في الطريق أيضًا.', 'Three copies and three testimonies agree. Adam sends an invitation to the meeting house. Liane, Murad and Sami are on their way.', 'Trois copies et trois témoignages concordent. Adam invite chacun à la maison de rencontre.'),
    npcs: [{ actor: 'ines', at: [-4, 12], companionAfter: 'i-ines', activity: 'work', ambient: L('إيناس: يسمون هذا فيضانًا طبيعيًا. أجهزة القياس تحكي عن بوابة فُتحت عمدًا.', 'Ines: They call this a natural flood. The instruments show a gate opened deliberately.', 'Inès : Ils parlent d’une crue naturelle. Les instruments montrent une vanne ouverte volontairement.') }],
    objectives: [
      talk('i-ines', 'ines', [-4, 12], L('رافق إيناس إلى النهر', 'Meet Ines by the river', 'Retrouvez Inès au fleuve'), [L('أملك إذن أخذ العينات، وسأرافقك. اقترب من الماء وخذ سجل المنسوب، ثم نقارنه بمحطة المضخة. يمكنك السباحة وSpace للخروج.', 'I have the sampling permit and will come with you. Recover the water-level log and compare it to the pump station. Swim if needed; Space to leave the water.', 'J’ai l’autorisation de prélèvement. Prenons le relevé et comparons-le à la pompe. Vous pouvez nager ; Espace pour sortir.')]),
      reach('i-bank', [0, -14], L('استكشف ضفة النهر', 'Explore the riverbank', 'Explorez la rive')),
      inspect('i-sample', [-7, -23], L('استعد سجل المنسوب من الماء', 'Retrieve the water-level log', 'Récupérez le relevé dans l’eau'), L('وصل تدفق مفاجئ من منظومة أطلس في اليوم نفسه الذي جفت فيه آبار نمار. الماء لم يختفِ؛ جرى تحويله.', 'A surge arrived from Atlas on the same day Namar’s wells ran dry. The water did not vanish. It was diverted.', 'Un afflux Atlas est arrivé le jour où Namar s’est asséchée. L’eau a été détournée.')),
      inspect('i-pump', [8, -43], L('افحص سجل محطة المضخة', 'Inspect the pump-station log', 'Examinez le registre de la pompe'), L('أمر التحويل يحمل رمز الإدارة «ظل / 17» وتوقيع ناصر. سجل إيفارا يكمل التاريخ والعقد والضرر في سلسلة إثبات واحدة.', 'The diversion order bears management code “Shadow / 17” and Nacer’s signature. Ivara joins date, contract and harm in a single chain of evidence.', 'L’ordre porte le code « Ombre / 17 » et la signature de Nacer. Ivara complète la chaîne de preuves.')),
      talk('i-goodbye', 'ines', [0, -43], L('وثّق النتائج مع إيناس', 'Certify the findings with Ines', 'Certifiez les résultats avec Inès'), [L('وقعت الشهادة وسأرسلها إلى الجهات المختصة. أخبر ريان أن قياساته أنقذت قرى لا يعرف أسماءها.', 'I have signed the testimony and sent it to the authorities. Tell Rayan his measurements saved villages he has never seen.', 'J’ai signé et transmis le témoignage aux autorités. Dis à Rayan que ses mesures ont sauvé des villages inconnus.')]),
      leave('i-depart', [0, -69], L('عد للقاء الحلفاء', 'Return to meet your allies', 'Rejoignez vos alliés')),
    ],
  },
  {
    id: 'allies', chapter: 10, title: L('طاولة الآفاق', 'The Table of Horizons', 'La table des horizons'), place: L('بيت اللقاء', 'The meeting house', 'La maison de rencontre'), country: taz, biome: 'allies', image: '/images/algiers-hero.jpg', map: [382, 265], day: 24, span: 86, weather: 'clear',
    intro: L('للمرة الأولى يجتمع كل من جعل الطريق ممكنًا. ليان تحمل خريطة الجبال، ومراد يفحص الأرقام، وسامي وصل برسالة من القرية، وآدم يرتب الشهادات.', 'For the first time, everyone who made the journey possible is together. Liane brings maps, Murad the numbers, Sami news from home, and Adam the testimonies.', 'Pour la première fois, tous les alliés sont réunis : cartes, chiffres, nouvelles du village et témoignages.'),
    outro: L('كل الطرق تشير إلى المرصد القديم في الجزائر. لكن سامي يحمل خبرًا أهم: عاد ريان إلى البيت تحت حماية الشهود. حان وقت العودة.', 'Every route points to the old observatory in Algeria. Sami has more important news: Rayan is safely home under witness protection. It is time to return.', 'Tout mène au vieil observatoire en Algérie. Sami annonce que Rayan est rentré, protégé. Il est temps de revenir.'),
    npcs: [
      { actor: 'liane', at: [-5, -6], ambient: L('ليان: هنا يلتقي الطريقان. مراد: والرقم 17 في قلب التقاطع.', 'Liane: The two routes meet here. Murad: With number 17 at their center.', 'Liane : Les deux routes se croisent ici. Mourad : Et le nombre 17 est au centre.') },
      { actor: 'murad', at: [5, -6], ambient: L('كل نسخة وحدها ظن، ومعًا تصبح دليلًا.', 'Each copy alone is a suspicion. Together they become proof.', 'Seule, chaque copie est un soupçon. Ensemble, elles deviennent une preuve.') },
      { actor: 'sami', at: [-5, -21], ambient: L('وصلت رسالة من البيت. هذه المرة تحمل خبرًا طيبًا.', 'A message came from home. This time, it is good news.', 'Un message de la maison. Cette fois, une bonne nouvelle.') },
      { actor: 'adam', at: [5, -21], ambient: L('لن ننشر اسم شاهد دون رضاه. الحقيقة تحتاج حماية أصحابها.', 'We publish no witness’s name without consent. Truth must protect its tellers.', 'Aucun nom de témoin sans consentement. La vérité protège ceux qui la disent.') },
    ],
    objectives: [
      talk('a-liane', 'liane', [-5, -6], L('راجع طريق الجبال مع ليان', 'Review the mountain route with Liane', 'Revoyez la route avec Liane'), [L('الطريق الذي اختفى منه ريان يعود إلى مرصد قديم. لا يظهر في الخرائط الحديثة، لكنه في مخطط أطلس الأول.', 'Rayan’s last mountain route leads to an old observatory. It is absent from new maps but appears in Atlas’s first plans.', 'Le dernier chemin de Rayan mène à un ancien observatoire, présent seulement sur les premiers plans Atlas.')]),
      talk('a-murad', 'murad', [5, -6], L('حلل القياسات مع مراد', 'Analyze the measurements with Murad', 'Analysez les mesures avec Mourad'), [L('الظل الأسود اسم لشبكة التعاقد التي بناها ناصر. لم يكن يبيع الماء وحده، بل حق القرى في الوصول إليه. المرصد مركز التحكم.', 'The Black Shadow is Nacer’s contracting network. He was selling not just water, but villages’ rights to it. The observatory is its control center.', 'L’Ombre noire est le réseau de contrats de Nacer. Il vendait le droit des villages à l’eau. L’observatoire est le centre de contrôle.')]),
      talk('a-sami', 'sami', [-5, -21], L('اسمع خبر سامي من البيت', 'Hear Sami’s news from home', 'Écoutez les nouvelles de Sami'), [L('ريان في البيت يا ياسين. حين ثبتت الشهادات، تمكن من العودة تحت الحماية. لم يتصل حتى لا يكشف مكان من أخفوه. أمك تنتظركما.', 'Rayan is home, Yassine. The verified testimony let him return under protection. He stayed silent to protect those who sheltered him. Your mother is waiting.', 'Rayan est rentré sous protection grâce aux témoignages. Il gardait le silence pour protéger ceux qui l’abritaient. Votre mère vous attend.')]),
      talk('a-adam', 'adam', [5, -21], L('اجمع الشهادات مع آدم', 'Assemble the testimonies with Adam', 'Rassemblez les témoignages avec Adam'), [L('أرسلت النسخ للجهات المختصة. نحتاج سجل المرصد لإغلاق القضية، لا للانتقام. سنرافقك إلى النهاية.', 'The authorities have the copies. We need the observatory log to close the case, not for revenge. We are with you to the end.', 'Les autorités ont les copies. Il faut le registre de l’observatoire pour clore l’affaire, pas pour se venger. Nous t’accompagnons.')]),
      deduce('a-map', [0, -30], L('حدد الموقع النهائي على الخريطة', 'Pinpoint the final site on the map', 'Identifiez le site final sur la carte'), L('طريق ليان، رقم مراد، وختم العقود تلتقي في موضع واحد. أين مركز الظل؟', 'Liane’s route, Murad’s number and the charter seal converge. Where is the Shadow’s center?', 'La route, le nombre et le sceau convergent. Où se trouve le centre de l’Ombre ?'), [L('الميناء في أوردل', 'Aster Harbor in Ordel', 'Le port d’Aster à Ordel'), L('الواحة في نمار', 'Namar Oasis', 'L’oasis de Namar'), L('المرصد القديم في الجزائر', 'The old observatory in Algeria', 'Le vieil observatoire en Algérie')], 2),
      leave('a-depart', [0, -56], L('عد إلى الجزائر', 'Return to Algeria', 'Retournez en Algérie')),
    ],
  },
  {
    id: 'homecoming', chapter: 11, title: L('حين يعرفك الطريق', 'When the Road Remembers You', 'Quand le chemin vous reconnaît'), place: L('تاغزوت، بعد العودة', 'Taghzout, after the journey', 'Taghzout, au retour'), country: alg, biome: 'village', image: '/images/village-journey.jpg', map: [142, 146], day: 28, span: 90, weather: 'clear', returning: true,
    intro: L('الطريق نفسه، لكنه ليس المشهد نفسه. ساقية الماء تعمل، أعلام قماشية جديدة بين البيوت، وفي فناء العائلة شخص انتظر ياسين سماع صوته طويلًا.', 'The same road, but not the same scene. The water channel runs again. New cloth banners hang between the houses. A familiar voice waits in the family courtyard.', 'La même route, un autre paysage. L’eau coule de nouveau. Dans la cour familiale, une voix familière attend.'),
    outro: L('عاد الأخوان إلى البيت، لكن الحقيقة تحتاج آخر صفحة. مع المفتاح الذي حفظه ريان، يصعد ياسين إلى المرصد حيث ينتظر الظل.', 'Both brothers are home, but the truth needs its last page. With Rayan’s key, Yassine climbs toward the observatory.', 'Les deux frères sont rentrés, mais il reste une dernière page. Avec la clé de Rayan, Yassine rejoint l’observatoire.'),
    npcs: [{ actor: 'amina', at: [-3, 12], ambient: L('أمينة: أعدت الخبز مرتين اليوم. هذه المرة لن يبرد قبل أن تصلوا.', 'Amina: I baked twice today. This time it will not go cold before you arrive.', 'Amina : J’ai fait du pain deux fois. Cette fois, vous arriverez avant qu’il refroidisse.') }, { actor: 'rayan', at: [8, -13], ambient: L('ريان: صوت المضخة... لم أظن أنني سأسمعه من هذا الفناء مرة أخرى.', 'Rayan: The sound of the pump. I thought I might never hear it from this courtyard again.', 'Rayan : La pompe… Je ne pensais plus l’entendre depuis cette cour.') }, { actor: 'idris', at: [-7, -26], activity: 'rest', ambient: L('إدريس: البيت لا يكبر بجدرانه، بل بمن يعود إليه.', 'Idris: A home grows not by its walls, but by those who return.', 'Idris : Une maison grandit par ceux qui reviennent, pas par ses murs.') }],
    objectives: [
      talk('h-amina', 'amina', [-3, 12], L('عد إلى أمينة في فناء البيت', 'Reunite with Amina at home', 'Retrouvez Amina à la maison'), [L('لم أغلق الباب. كل رسالة وصلتني من أصدقائك كانت خطوة تقربكما. ريان ينتظرك عند الساقية؛ اذهب، ثم تعودان للعشاء.', 'I never locked the door. Every message from your friends brought you closer. Rayan is by the channel. Go, and come back together for supper.', 'Je n’ai jamais fermé la porte. Vos amis vous rapprochaient à chaque message. Rayan attend près du canal. Revenez ensemble pour dîner.')]),
      talk('h-rayan', 'rayan', [8, -13], L('التقِ ريان واعرف الحقيقة', 'Reunite with Rayan and learn the truth', 'Retrouvez Rayan et apprenez la vérité'), [L('اكتشفت أن ناصر يستعمل طائراته لإخفاء القياسات وشبكته لمحو القرى من العقود. احتجزني حين رفضت التوقيع. أخرجني أحد العمال، ثم أخفاني الشهود.', 'Nacer used drones to suppress measurements and contracts to erase villages. He detained me when I refused to sign. A worker helped me escape, then witnesses sheltered me.', 'Nacer effaçait les mesures et les villages. Il m’a retenu quand j’ai refusé de signer. Un ouvrier m’a aidé, puis les témoins m’ont protégé.'), L('تركت الأدلة موزعة كي لا يمحوها كلها. جمعتها أنت، وحميت من ساعدني. المفتاح في صندوق العائلة يفتح سجل المرصد.', 'I scattered the evidence so he could not erase all of it. You found it and protected those who helped me. Our family chest holds the observatory key.', 'J’ai dispersé les preuves pour les préserver. Tu les as réunies et protégé mes soutiens. La clé de l’observatoire est dans notre coffre.')]),
      talk('h-idris', 'idris', [-7, -26], L('زر إدريس مرة أخرى', 'Visit Idris again', 'Retrouvez Idris'), [L('عدت تحمل أسماء أصدقاء لا أسماء أعداء. هذا ما يجعل الرحلة تستحق. خذ المفتاح من الصندوق، وليكن آخر الطريق بداية للناس.', 'You came back carrying friends’ names, not enemies’ names. That made the journey worthwhile. Take the key and let this ending become a beginning for everyone.', 'Tu reviens avec des noms d’amis. Voilà le sens du voyage. Prends la clé, et que cette fin soit un commencement.')]),
      inspect('h-key', [0, -39], L('استلم مفتاح المرصد', 'Take the observatory key', 'Prenez la clé de l’observatoire'), L('مفتاح ريان يفتح النسخة الأصلية لسجل التحكم. معه رسالة: «انشر الحقيقة، لا تكرر الخوف».', 'Rayan’s key opens the original control log. His note reads: “Publish the truth. Do not repeat the fear.”', 'La clé ouvre le registre original. Rayan écrit : « Publie la vérité. Ne reproduis pas la peur. »')),
      leave('h-depart', [0, -58], L('اصعد إلى المرصد السري', 'Ascend to the hidden observatory', 'Montez à l’observatoire caché')),
    ],
  },
  {
    id: 'observatory', chapter: 12, title: L('أسد عند الفجر', 'A Lion at Dawn', 'Un lion à l’aube'), place: L('مرصد الأطلس القديم', 'The old Atlas observatory', 'Le vieil observatoire Atlas'), country: alg, biome: 'citadel', image: '/images/atlas-mountains.jpg', map: [192, 107], day: 29, span: 108, weather: 'clear', night: true,
    intro: L('فوق السحب، تبقى أضواء المرصد مشتعلة. الحلفاء يؤمّنون الطريق والجهات المختصة تنتظر السجل. لم يأت ياسين ليمحو أحدًا، بل ليمنع محو الحقيقة.', 'Above the clouds, the observatory is still lit. Allies secure the approach; the authorities await the log. Yassine has come to stop the truth being erased.', 'Au-dessus des nuages, l’observatoire brille encore. Les alliés sécurisent la route et les autorités attendent le registre.'),
    outro: L('انتهت سلطة الظل حين صار السجل ملكًا للجميع. تسلمت الجهات المختصة ناصر، وعاد الماء والأسماء إلى خرائط القرى.', 'The Shadow’s power ended when the record became public. The authorities took Nacer into custody. Water, and names, returned to the village maps.', 'Le pouvoir de l’Ombre prend fin avec la publication du registre. Nacer est remis aux autorités. L’eau et les noms reviennent sur les cartes.'),
    npcs: [{ actor: 'liane', at: [-4, 12], companionAfter: 'f-liane', ambient: L('ليان، عبر الراديو: الجميع في مواقعهم. مراد، هل يصل الإرسال؟ مراد: واضح. نحن معكم.', 'Liane, on radio: Everyone is in position. Murad, is the link clear? Murad: Clear. We are with you.', 'Liane : Tout le monde est en place. Mourad, le lien ? Mourad : Clair. Nous sommes avec vous.') }, { actor: 'shadow', at: [0, -70], activity: 'rest', ambient: L('ناصر: في النهاية، كل طريق يعود إلى هذا المكان.', 'Nacer: In the end, every road comes back to this place.', 'Nacer : Finalement, chaque route revient ici.') }],
    objectives: [
      talk('f-liane', 'liane', [-4, 12], L('نسّق الدخول مع ليان', 'Coordinate with Liane', 'Coordonnez l’approche avec Liane'), [L('سنوقف منظومة التعطيل، لا نمس السجل. افصل المرحلين ثم عطّل حارس المرصد. مراد يجهز بث الأدلة، وآدم مع الجهات المختصة.', 'Disable the two relays, then the observatory’s guardian drone. Leave the archive intact. Murad is preparing the evidence broadcast; Adam is with the authorities.', 'Désactive les deux relais puis le drone gardien. Préserve les archives. Mourad prépare la transmission, Adam est avec les autorités.')]),
      inspect('f-relay1', [-6, -14], L('افصل مرحّل الحجب الأول', 'Disconnect the first blocking relay', 'Déconnectez le premier relais'), L('انطفأ المرحّل الأول. بدأت نسخة آمنة من سجلات القرى تنتقل إلى مراد.', 'The first relay goes dark. A safe copy of the village registers begins reaching Murad.', 'Le premier relais s’éteint. Une copie des registres parvient à Mourad.')),
      inspect('f-relay2', [7, -30], L('افصل مرحّل الحجب الثاني', 'Disconnect the second blocking relay', 'Déconnectez le second relais'), L('انفتح مسار الإرسال. طائرة الحارس تحاول قطع الوصول إلى القلب.', 'The transmission path is open. The guardian drone tries to block access to the core.', 'La transmission est ouverte. Le drone gardien bloque l’accès au coeur.')),
      { id: 'f-guardian', kind: 'fight', at: [0, -48], title: L('عطّل حارس المرصد وطائراته', 'Disable the observatory guardian and drones', 'Neutralisez le gardien et ses drones'), detail: L('احتمِ بالصناديق. وجّه الكاميرا وأطلق بـF، وR للشحن. لا تستهدف الأشخاص.', 'Use cover. Face the drones and fire with F; R recharges. People are never targets.', 'Abritez-vous. Visez les drones avec F ; R recharge. Les personnes ne sont jamais des cibles.') },
      inspect('f-core', [-6, -52], L('افتح السجل بمفتاح ريان', 'Open the log with Rayan’s key', 'Ouvrez le registre avec la clé de Rayan'), L('السجل الكامل يثبت تحويل الماء وتزوير العقود وأمر احتجاز ريان. كل حلقة من رحلتك أصبحت دليلًا متصلًا.', 'The full log proves the diversion, the forged charters and Rayan’s detention order. Every part of your journey now forms one connected proof.', 'Le registre prouve les détournements, les faux contrats et la détention de Rayan. Toute la chaîne est complète.')),
      talk('f-shadow', 'shadow', [0, -70], L('واجه الظل بالحقيقة', 'Confront the Shadow with the truth', 'Confrontez l’Ombre à la vérité'), [L('ظننت أن من يتحكم بالماء يستطيع ترتيب العالم كما يشاء. أخوك رفض أن يجعل الناس أرقامًا، ثم جئت أنت تحمل أسماءهم كلها.', 'I thought whoever controlled water could arrange the world. Your brother refused to reduce people to numbers. Then you arrived carrying all their names.', 'Je pensais organiser le monde en contrôlant l’eau. Ton frère a refusé de réduire les gens à des chiffres. Tu as apporté leurs noms.'), L('لم يعد لدي ما أخفيه. السجل لك، وسأجيب أمام الجهات المختصة. لا تمحُ أسماء العمال الذين حاولوا المساعدة.', 'I have nothing left to hide. Take the log. I will answer to the authorities. Keep the names of the workers who tried to help.', 'Je n’ai plus rien à cacher. Prends le registre. Je répondrai aux autorités. Préserve les noms des ouvriers qui ont aidé.')]),
      { id: 'f-publish', kind: 'finish', at: [4, -77], title: L('انشر الأدلة وأنهِ رحلة الظل', 'Publish the evidence and end the Shadow’s hold', 'Publiez les preuves et mettez fin à l’Ombre'), detail: L('اضغط E عند منصة الإرسال لتسليم السجل إلى الجهات المختصة وفتح النهاية.', 'Press E at the transmitter to send the record to the authorities and begin the ending.', 'Appuyez sur E au transmetteur pour remettre le registre aux autorités et lancer la fin.') },
    ], enemies: [{ at: [5, -19], hp: 2, from: 1 }, { at: [-7, -32], hp: 2, from: 2 }, { at: [5, -45], hp: 3, from: 3 }, { at: [-1, -49], hp: 8, from: 3, boss: true }],
  },
];

export const EPILOGUE = [
  { image: '/images/village-journey.jpg', title: L('البيت، أخيرًا', 'Home, at last', 'Enfin, la maison'), body: L('عاد ياسين وريان إلى فناء أمينة. صارت قياسات ريان معلنة للسكان، ولم يعد مصباح البيت علامة انتظار بل علامة ترحيب.', 'Yassine and Rayan return to Amina’s courtyard. Rayan makes his measurements public. The light at home now means welcome, not waiting.', 'Yassine et Rayan retrouvent Amina. Les mesures deviennent publiques. La lumière signifie désormais bienvenue.') },
  { image: '/images/atlas-mountains.jpg', title: L('طرق لا تنتهي', 'Paths that keep going', 'Des chemins qui continuent'), body: L('فتحت ليان دروب الجبال للباحثين. أسس مراد وسامي ورشة تصلح مضخات القرى، وتعلم الصغار كيف يسألون عن الأرقام.', 'Liane opens mountain trails to researchers. Murad and Sami build a workshop that repairs village pumps and teaches children to question the numbers.', 'Liane ouvre les sentiers aux chercheurs. Mourad et Sami réparent les pompes et apprennent aux enfants à interroger les chiffres.') },
  { image: '/images/ivara-river.jpg', title: L('أصدقاء أبعد من الحدود', 'Friends beyond borders', 'Des amis au-delà des frontières'), body: L('نشر آدم تحقيقًا بأسماء من وافقوا على الظهور. حفظت ميرا ورين وإيناس نسخ الأدلة في أرشيفات عامة، وبقي أزل يوصل المسافرين إلى نمار.', 'Adam publishes with the witnesses’ consent. Mira, Ren and Ines preserve the evidence in public archives. Azel still guides travelers to Namar.', 'Adam publie avec le consentement des témoins. Mira, Ren et Inès préservent les archives. Azel guide encore les voyageurs.') },
  { image: '/images/oasis-night.jpg', title: L('العالم ينتظرك', 'The world is still yours', 'Le monde vous attend'), body: L('انتهت الحكاية، لا الرحلة. جميع المناطق مفتوحة الآن: زر الأصدقاء، اجمع الذكريات، وقد مركبتك حيث يقودك الطريق. السفر الحر من خريطة الرحلة.', 'The story ends, not the journey. Every region is now open. Visit your friends, collect memories and drive wherever the road leads. Use the journey atlas to travel freely.', 'L’histoire finit, pas le voyage. Visitez vos amis, collectionnez les souvenirs et voyagez librement depuis l’atlas.') },
];

export const defaultJourney = (): JourneyProgress => ({ region: 0, step: 0, completed: [], visited: [0], met: [], evidence: [], souvenirs: [], finished: false, elapsed: 0, chaseRemaining: 0 });

export function validJourneySave(value: unknown): value is SavedRun {
  if (!value || typeof value !== 'object') return false;
  const run = value as SavedRun;
  const j = run.journey;
  const point = (v: unknown): boolean => Array.isArray(v) && v.length === 3 && v.every(n => typeof n === 'number' && Number.isFinite(n));
  const strings = (v: unknown): boolean => Array.isArray(v) && v.every(item => typeof item === 'string');
  return run.version === 2 && !!j && Number.isInteger(j.region) && j.region >= 0 && j.region < CAMPAIGN.length
    && Number.isInteger(j.step) && j.step >= 0 && j.step <= CAMPAIGN[j.region].objectives.length
    && strings(j.completed) && Array.isArray(j.visited) && j.visited.every(n => Number.isInteger(n) && n >= 0 && n < CAMPAIGN.length)
    && strings(j.met) && strings(j.evidence) && strings(j.souvenirs) && typeof j.finished === 'boolean'
    && point(run.position) && Number.isFinite(run.yaw)
    && Number.isFinite(run.health) && run.health > 0 && Number.isFinite(run.score) && Number.isFinite(run.xp)
    && Number.isFinite(j.elapsed) && Number.isFinite(j.chaseRemaining) && Number.isFinite(run.kills) && Number.isFinite(run.bestCombo)
    && Number.isFinite(run.ammo) && (run.weapon === 'azru' || run.weapon === 'sirocco')
    && Array.isArray(run.enemies) && run.enemies.every(Number.isFinite) && Array.isArray(run.targets) && run.targets.every(Number.isFinite) && Array.isArray(run.relics)
    && (!j.vehicle || (point(j.vehicle.position) && Number.isFinite(j.vehicle.yaw) && Number.isFinite(j.vehicle.integrity) && typeof j.vehicle.driving === 'boolean'))
    && (!j.trail || (Array.isArray(j.trail) && j.trail.every(point)))
    && (!j.companions || (typeof j.companions === 'object' && Object.values(j.companions).every(c => c && point(c.position) && Number.isInteger(c.trail) && c.trail >= 0)));
}

export function validateCampaign() {
  const ids = new Set<string>();
  for (const region of CAMPAIGN) {
    const exit = region.objectives[region.objectives.length - 1];
    if (exit?.kind !== 'travel' && exit?.kind !== 'finish') throw new Error(`Missing chapter exit: ${region.id}`);
    for (const npc of region.npcs) {
      if (!ACTORS[npc.actor]) throw new Error(`Unknown actor: ${npc.actor}`);
      if (npc.companionAfter && !region.objectives.some(o => o.id === npc.companionAfter)) throw new Error(`Invalid companion introduction: ${npc.actor}`);
    }
    for (const objective of region.objectives) {
      if (ids.has(objective.id)) throw new Error(`Duplicate objective: ${objective.id}`);
      ids.add(objective.id);
      if (objective.actor && !region.npcs.some(n => n.actor === objective.actor)) throw new Error(`Missing NPC: ${objective.id}`);
      if (objective.choices && objective.choices.filter(c => c.correct).length !== 1) throw new Error(`Invalid deduction: ${objective.id}`);
      if (!objective.at.every(Number.isFinite) || objective.at[1] < 26 - region.span || objective.at[1] > 27) throw new Error(`Objective outside the playable region: ${objective.id}`);
      if (objective.kind === 'drive' && !region.vehicle) throw new Error(`Missing mission vehicle: ${objective.id}`);
      if (objective.kind === 'talk' && !objective.lines?.length) throw new Error(`Missing story conversation: ${objective.id}`);
      for (const language of ['ar', 'en', 'fr'] as const) if (!objective.title[language] || !objective.detail[language]) throw new Error(`Missing ${language} objective translation: ${objective.id}`);
    }
  }
  if (new Set(CAMPAIGN.map(r => r.chapter)).size !== 12) throw new Error('The campaign must contain twelve connected chapters.');
  if (CAMPAIGN.length !== 14) throw new Error('The journey must contain fourteen regional stops.');
}