import { L, local } from './campaign';
import type { Language } from './types';

const labels = {
  journey: L('دفتر الرحلة', 'Journey journal', 'Carnet de voyage'),
  atlas: L('أطلس الرحلة', 'The journey atlas', 'L’atlas du voyage'),
  chapter: L('الفصل', 'CHAPTER', 'CHAPITRE'),
  day: L('اليوم', 'DAY', 'JOUR'),
  stages: L('محطات الرحلة', 'Journey stops', 'Étapes du voyage'),
  campaign: L('حملة القصة / 12 فصلًا', 'STORY CAMPAIGN / 12 CHAPTERS', 'CAMPAGNE / 12 CHAPITRES'),
  subtitle: L('من أول أثر في القرية، إلى آخر ضوء خلف الحدود.', 'From a village’s first clue to the light beyond borders.', 'D’un indice au village à la lumière au-delà des frontières.'),
  begin: L('ابدأ الحكاية', 'Begin the story', 'Commencer l’histoire'),
  next: L('تابع الحوار', 'Continue', 'Continuer'),
  finishTalk: L('لنواصل الطريق', 'Let’s keep going', 'Reprenons la route'),
  closeTalk: L('أنهِ الحديث الآن', 'Leave conversation', 'Quitter la conversation'),
  talk: L('تحدث مع', 'Speak with', 'Parler avec'),
  inspect: L('افحص الدليل', 'Examine the evidence', 'Examiner l’indice'),
  deduce: L('اربط الأدلة', 'Connect the evidence', 'Relier les indices'),
  travel: L('تابع الرحلة', 'Continue the journey', 'Poursuivre le voyage'),
  ending: L('افتح الصفحة الأخيرة', 'Turn the final page', 'Tourner la dernière page'),
  enterVehicle: L('اركب أسفار', 'Enter Asfar', 'Monter dans Asfar'),
  exitVehicle: L('توقف وانزل', 'Stop and leave vehicle', 'Arrêter et descendre'),
  repairVehicle: L('أصلح أسفار', 'Repair Asfar', 'Réparer Asfar'),
  driving: L('أسفار / قيادة', 'ASFAR / DRIVING', 'ASFAR / CONDUITE'),
  brake: L('فرامل', 'Brake', 'Freiner'),
  integrity: L('حالة المركبة', 'VEHICLE INTEGRITY', 'ÉTAT DU VÉHICULE'),
  companion: L('يرافقك', 'TRAVELING WITH YOU', 'VOUS ACCOMPAGNE'),
  checkpoint: L('حُفظت الرحلة', 'Journey saved', 'Voyage sauvegardé'),
  objectiveComplete: L('خطوة أقرب إلى الحقيقة', 'One step closer to the truth', 'Un pas vers la vérité'),
  clue: L('أضيف إلى دفتر الأدلة', 'Added to the evidence journal', 'Ajouté au carnet de preuves'),
  memory: L('ذكرى من الطريق', 'A memory from the road', 'Un souvenir du chemin'),
  people: L('وجوه من الطريق', 'Faces along the way', 'Rencontres en chemin'),
  evidence: L('خيوط الحقيقة', 'Threads of the truth', 'Les fils de la vérité'),
  local: L('خريطة المنطقة', 'Regional map', 'Carte régionale'),
  itinerary: L('مسار الحكاية', 'Story itinerary', 'Itinéraire narratif'),
  atlasDesc: L('قرية، جبال، صحراء، ثم آفاق جديدة. تتكشف الخريطة مع كل خطوة.', 'A village, mountains, desert, then new horizons. The atlas unfolds with every step.', 'Un village, des montagnes, le désert, puis de nouveaux horizons. L’atlas se dévoile à chaque étape.'),
  journalDesc: L('الأدلة التي وجدتها والأشخاص الذين عرفتهم. لا تُكشف الصفحات قبل وقتها.', 'The evidence you found and the people you met. No pages are revealed before their time.', 'Les indices trouvés et les personnes rencontrées. Aucune page n’est révélée trop tôt.'),
  evidenceEmpty: L('أول خيط ينتظرك قرب بئر القرية.', 'The first thread waits beside the village well.', 'Le premier fil vous attend au puits du village.'),
  peopleEmpty: L('تحدث مع إدريس تحت شجرة الزيتون لتبدأ الرحلة.', 'Speak to Idris beneath the olive tree to begin.', 'Parlez à Idris sous l’olivier pour commencer.'),
  done: L('مكتمل', 'COMPLETED', 'TERMINÉ'),
  current: L('أنت هنا', 'YOU ARE HERE', 'VOUS ÊTES ICI'),
  locked: L('يتكشف مع تقدم الحكاية', 'Revealed as the story unfolds', 'Révélé au fil de l’histoire'),
  known: L('سبق استكشافه', 'Previously explored', 'Déjà exploré'),
  hidden: L('آفاق لم تُكتشف بعد', 'Horizons yet to be discovered', 'Des horizons à découvrir'),
  returnToStory: L('عد إلى الحكاية', 'Return to the story', 'Reprendre l’histoire'),
  enterRegion: L('ابدأ من القرية', 'Begin in the village', 'Commencer au village'),
  visit: L('سافر إلى هذه المنطقة', 'Travel to this region', 'Voyager vers cette région'),
  fastTravelLocked: L('السفر الحر يتاح بعد نهاية القصة. تابع الطريق الطبيعي بين الفصول.', 'Free travel unlocks after the ending. Follow the story’s physical route between chapters.', 'Le voyage libre se débloque après la fin. Suivez le chemin de l’histoire entre les chapitres.'),
  freeExplore: L('استكشف العالم بحرية', 'Explore the world freely', 'Explorer le monde librement'),
  freeExploreTitle: L('الحكاية انتهت. الطريق مستمر.', 'The story ends. The road goes on.', 'L’histoire finit. La route continue.'),
  freeExploreDetail: L('زر الأصدقاء واجمع الذكريات. افتح M للسفر بين كل المناطق دون إعادة المهمات.', 'Visit friends and collect memories. Open M to travel between every region without replaying missions.', 'Visitez vos amis et trouvez les souvenirs. M ouvre le voyage libre sans rejouer les missions.'),
  nextRegion: L('إلى الأفق التالي', 'To the next horizon', 'Vers le prochain horizon'),
  nextScene: L('المشهد التالي', 'Next scene', 'Scène suivante'),
  skip: L('تخطي الانتقال', 'Skip transition', 'Passer la transition'),
  transition: L('على امتداد الطريق', 'ALONG THE ROAD', 'AU FIL DU CHEMIN'),
  official: L('عبور رسمي معتمد', 'OFFICIAL PASSAGE APPROVED', 'PASSAGE OFFICIEL APPROUVÉ'),
  fiction: L('خريطة قصصية. الدول والمسارات الخارجية خيالية وليست إرشادات سفر.', 'A story atlas. Foreign countries and routes are fictional, not travel directions.', 'Atlas narratif. Les pays et routes sont fictifs, pas des indications de voyage.'),
  campaignLength: L('12 فصلًا / 14 منطقة قابلة للعب', '12 CHAPTERS / 14 PLAYABLE REGIONS', '12 CHAPITRES / 14 RÉGIONS JOUABLES'),
  wrong: L('راجع الشهادات مرة أخرى. هذا الاستنتاج لا يجمع كل الأدلة. يمكنك المحاولة دون عقوبة.', 'Look at the testimonies again. This conclusion does not explain every clue. Try again without a penalty.', 'Relisez les témoignages. Cette conclusion n’explique pas tous les indices. Réessayez sans pénalité.'),
  crouchFirst: L('انحنِ أولًا بـC لتفحص الأرشيف من خلف الساتر.', 'Crouch with C first to examine the archive behind cover.', 'Accroupissez-vous avec C pour examiner l’archive à couvert.'),
  chapterLocked: L('أكمل أدلة هذه المنطقة قبل متابعة الطريق.', 'Complete this region’s evidence before continuing.', 'Complétez les indices de cette région avant de continuer.'),
  voices: L('قراءة الحوار بصوت الجهاز', 'Read dialogue with device voices', 'Lire les dialogues avec les voix de l’appareil'),
  regionalWeather: L('طقس المنطقة الطبيعي', 'Regional weather', 'Météo de la région'),
  nightNote: L('أجواء كل منطقة تتغير مع الرحلة. مهمتا الواحة والمرصد تبدأان ليلًا وفق أحداث القصة.', 'Each region has its own atmosphere. The oasis and observatory missions take place at night as part of the story.', 'Chaque région possède son atmosphère. Les missions de l’oasis et de l’observatoire se déroulent de nuit.'),
  journeySummary: L('عرض خلاصة الرحلة', 'View journey summary', 'Voir le bilan du voyage'),
  voiceNote: L('تُستخدم الأصوات المحلية المتاحة فقط. إن لم يتوفر صوت للغة المختارة، يبقى الحوار مكتوبًا.', 'Uses available local device voices only. If your language has no installed voice, dialogue remains subtitled.', 'Utilise uniquement les voix locales. Sans voix installée pour la langue, les dialogues restent sous-titrés.'),
  retry: L('عد إلى آخر نقطة آمنة', 'Return to the last safe checkpoint', 'Revenir au dernier point sûr'),
  recover: L('الطريق ينتظرك من جديد', 'The road is waiting again', 'La route vous attend encore'),
  lossDetail: L('لم تضِع الأدلة أو الفصول المكتملة. تابع من آخر نقطة آمنة.', 'Your evidence and completed chapters are safe. Continue from the last safe checkpoint.', 'Vos preuves et chapitres terminés sont conservés. Reprenez au dernier point sûr.'),
  newConfirm: L('تبدأ الحكاية من القرية من جديد. تُستبدل نقطة حفظ الحملة، وتبقى تجهيزاتك وخبرتك وأرقامك.', 'Begin again in the village. Your campaign checkpoint is replaced; equipment, lifetime XP and records remain.', 'Recommencez au village. Le point de campagne est remplacé ; équipement, XP et records restent.'),
  afterStory: L('مضت أيام على سقوط الشبكة. عاد الماء إلى القرى وبقي الأصدقاء على اتصال. يسعدني أن أراك تسافر دون خوف.', 'Days have passed since the network fell. Water returned to the villages and our friends stayed in touch. It is good to see you travel without fear.', 'L’eau est revenue et les amis sont restés en contact. Quel plaisir de vous voir voyager sans peur.'),
  goal: L('ابدأ بالحديث مع إدريس. تتبع الأهداف الذهبية، قابل الشهود وافحص الأدلة بـE. الرحلة بلا مؤقت عام؛ السباق مع الوقت يبدأ فقط أثناء المطاردة. M للخريطة وJ لدفتر الأدلة.', 'Begin with Idris. Follow gold objectives, meet witnesses and inspect evidence with E. There is no overall time limit; only the chase is timed. M opens the map, J the journal.', 'Commencez avec Idris. Suivez les objectifs dorés et examinez les preuves avec E. Seule la poursuite est chronométrée. M ouvre la carte, J le carnet.'),
  synopsis: L('عاد ياسين إلى قريته بحثًا عن أخيه ريان. يقوده دفتر قياسات الماء إلى شبكة تعبر الحدود، وإلى أصدقاء يجعلون كل طريق ممكنًا.', 'Yassine returns to his village to find his brother Rayan. A water-measurement notebook leads to a network spanning borders, and friends who make each road possible.', 'Yassine revient au village chercher Rayan. Un carnet le mène à un réseau au-delà des frontières et à de nouveaux amis.'),
  sprint: L('اركض إلى العلامة', 'Sprint to the marker', 'Courez vers le repère'),
  distance: L('م', 'm', 'm'),
  cluesFound: L('أدلة موثقة', 'EVIDENCE RECORDED', 'PREUVES CONSIGNÉES'),
  journeyTime: L('زمن الرحلة', 'JOURNEY TIME', 'DURÉE DU VOYAGE'),
  chapterCount: L('فصول مكتملة', 'CHAPTERS COMPLETED', 'CHAPITRES TERMINÉS'),
};

export type JourneyKey = keyof typeof labels;
export const jt = (language: Language, key: JourneyKey) => local(labels[key], language);